### ISSUE TITLE
Movement Functions should be moved to FixedUpdate()

### ISSUE THREAD

**Issue by prodskimaya** [RugbugRedfern/FPS-Game-Tutorial#4]
Problem: Movement functions in PlayerController.cs are currently in the Update() function, which means players with higher fps can run faster, jump higher, and ect.

Solution: Add movement functions to the FixedUpdate().

P.S: This may have a slim chance just to be a bug in my source code, but I checked the Github source and don't think it is.

Images included is how I solved it (may not be optimal):

![Screenshot (225)](https://user-images.githubusercontent.com/68769498/111749844-5f2db100-8860-11eb-80fa-195784170a70.png)
![Screenshot (226)](https://user-images.githubusercontent.com/68769498/111749855-62c13800-8860-11eb-834f-d6d9d02d0258.png)

**Comment by RugbugRedfern** [comment]
The player does not move faster or jump higher, because movement _is_ actually done in FixedUpdate already, on this line:
`rb.MovePosition(rb.position + transform.TransformDirection(moveAmount) * Time.fixedDeltaTime);`

And jump is a one time force, which does not scale based on the framerate.

The Move function **only gets movement input and smooths it**, it does not move the player.

I agree there are flaws with the PlayerController, but this is not the solution to change them. The solution you have provided means camera rotation and movement will be clamped at 50fps, which will make it feel unresponsive and choppy. Gathering input in FixedUpdate is also a bad idea as in Unity the input is calculated right before Update, so by gathering it in FixedUpdate you will miss many inputs.
